
# Flask-Restplus settings
RESTPLUS_SWAGGER_UI_DOC_EXPANSION = 'list'
RESTPLUS_VALIDATE = True
RESTPLUS_MASK_SWAGGER = False
RESTPLUS_ERROR_404_HELP = False

APP_ENVIRONMENT_SETTINGS = "production"
SECRET = "a-long-string-of-random-characters-CHANGE-TO-YOUR-LIKING"
